# -*- coding: utf-8 -*-
"""Maxsus topshiriq

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FyHIzz7tTzA7grDCmq7CThocvoUzhlJq
"""

df = pd.read_csv("WHO COVID-19 cases.csv")
print(df.head())

print(df)
filter = df[df['Cumulative_deaths'] == "Covid 19"]
print(filter)

print(df)
filter = df[df['Cumulative_deaths'] == "Covid 19"]
print(filter)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("img1.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("img2.jfif")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("img3.jfif")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("img4.jfif")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)